# -----------------------------------------------------------------------------
# CppAD: C++ Algorithmic Differentiation: Copyright (C) 2003-20 Bradley M. Bell
#
# CppAD is distributed under the terms of the
#              Eclipse Public License Version 2.0.
#
# This Source Code may also be made available under the following
# Secondary License when the conditions for such availability set forth
# in the Eclipse Public License, Version 2.0 are satisfied:
#       GNU General Public License, Version 2.0 or later.
# -----------------------------------------------------------------------------
#
sudo:     false
language: cpp
compiler: gcc

script:
  # bin/travis.sh (make|test_one) target1 target2 ...
  #
  bin/travis.sh make check install uninstall

notifications:
  email:
    recipients:
      bradbell@seanet.com
    on_success: change # send e-mail what success status changes
    on_failure: always # always send e-mail when a test fails
